title: Reddit Topic Telescope
description: Report for Document Analysis course - Reddit Topics and Sentiment Analysis
logo: dashboard/Llama.svg
show_downloads: True
dashboard_url: dashboard
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
